kind: Service
apiVersion: v1
metadata:
  name: playfab-auth
spec:
  selector:
    app: playfab-auth
  ports:
  - protocol: TCP
    name: 'http1'
    port: 80
    targetPort: 9001
  - protocol: TCP
    name: 'grpc'
    port: 4000
    targetPort: 9000
  type: LoadBalancer
  loadBalancerIP: "34.76.117.115" # Update
